name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHP ${{ matrix.php }}; Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
        laravel: ['5.5', '5.6', '5.7', '5.8', '6', '7', '8', '9', '10']
        exclude:
          - php: '7.1'
            laravel: '10'
          - php: '7.2'
            laravel: '10'
          - php: '7.3'
            laravel: '10'
          - php: '7.4'
            laravel: '10'
          - php: '8.0'
            laravel: '10'
          - php: '7.1'
            laravel: '6'
          - php: '7.1'
            laravel: '7'
          - php: '7.1'
            laravel: '8'
          - php: '7.1'
            laravel: '9'
          - php: '7.2'
            laravel: '8'
          - php: '7.2'
            laravel: '9'
          - php: '7.3'
            laravel: '9'
          - php: '7.4'
            laravel: '9'
          - php: '8.0'
            laravel: '5.5'
          - php: '8.0'
            laravel: '5.6'
          - php: '8.0'
            laravel: '5.7'
          - php: '8.0'
            laravel: '5.8'
          - php: '8.1'
            laravel: '5.5'
          - php: '8.1'
            laravel: '5.6'
          - php: '8.1'
            laravel: '5.7'
          - php: '8.1'
            laravel: '5.8'
          - php: '8.1'
            laravel: '6'
          - php: '8.1'
            laravel: '7'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, pdo_sqlite 
          tools: composer:v2
          coverage: none

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Select Laravel 5.5
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:5.5.*" "phpunit/phpunit:^6.5.14" --no-update --no-interaction
        if: "matrix.laravel == '5.5'"

      - name: Select Laravel 5.6
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:5.6.*" "phpunit/phpunit:^7.5.20" --no-update --no-interaction
        if: "matrix.laravel == '5.6'"

      - name: Select Laravel 5.7
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:5.7.*" "phpunit/phpunit:^7.5.20" --no-update --no-interaction
        if: "matrix.laravel == '5.7'"

      - name: Select Laravel 5.8
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:5.8.*" "phpunit/phpunit:^7.5.20|^8.5.8" --no-update --no-interaction
        if: "matrix.laravel == '5.8'"

      - name: Select Laravel 6
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:6.*" "phpunit/phpunit:^8.5.8|^9.3.7" --no-update --no-interaction
        if: "matrix.laravel == '6'"

      - name: Select Laravel 7
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:7.*" "phpunit/phpunit:^8.5.8|^9.3.7" --no-update --no-interaction
        if: "matrix.laravel == '7'"

      - name: Select Laravel 8
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:8.*" "phpunit/phpunit:^9.3.7" --no-update --no-interaction
        if: "matrix.laravel == '8'"

      - name: Select Laravel 9
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:9.*" "phpunit/phpunit:^9.5" --no-update --no-interaction
        if: "matrix.laravel == '9'"

      - name: Install PHP Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Execute PHPUnit
        run: vendor/bin/phpunit
